deliverable 0 for Boston 15-minute city
BU-Spark/CS506Spring2021Repository pull request #17
Opened 2021-02-20 04:02 UTC by mcxxmc

2021-02-23 16:18 UTC, gallettilance requested changes
please nest your pdf within a folder named after your project instead of having the file in the root of the repository

2021-02-24 11:51 UTC, mcxxmc commented
Hi I have put all things in a folder

2021-02-25 14:43 UTC, gallettilance approved these changes

2021-03-08 09:38 UTC, mcxxmc commented
Hi professor
I include the deliverable 1 here
Since the previous request has not been merged, the request is updated now and I am wondering when it will get merged?
Thank you very much!

2021-03-12 05:14 UTC, merged