Deliverable 0 and SCRUM report week 0
BU-Spark/CS506Spring2021Repository pull request #20
Opened 2021-02-22 14:41 UTC by cody9898

Drift Diffusion Models of children's interactions in a Repeated Prisoner's Dilemma Game - Team 2

2021-02-23 16:17 UTC, gallettilance requested changes
please upload a pdf instead and nest it within a folder that is named after your project name instead of "deliverable0"

2021-02-23 17:15 UTC, cody9898 commented
@gallettilance should the SCRUM reports folder also be inside the project name folder or should I leave that as is?

2021-02-23 20:48 UTC, gallettilance requested changes
please nest the scrum reports folder inside your team folder

2021-02-25 14:43 UTC, gallettilance approved these changes

2021-02-25 17:26 UTC, merged